apiVersion: v1
kind: Service
metadata:
  name: staliaswarden
  namespace: stalwart
  labels:
    app.kubernetes.io/name: staliaswarden
    app: staliaswarden
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: staliaswarden
    app: staliaswarden

